name: Backend Pull Request Check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

permissions:
  contents: read

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: 'backend/go.sum'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          working-directory: backend
          args: --timeout 5m
