name: Docker Build and Push

on:
  push:
    branches:
      - admin-*
      - app-*
      - main
    tags:
      - "admin-v[0-9]+.[0-9]+.[0-9]+*"
      - "app-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  docker-admin-build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/admin-') || startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/admin-v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        if: startsWith(github.ref, 'refs/tags/admin-v')
        uses: docker/login-action@v3
        with:
          registry: chaitin-registry.cn-hangzhou.cr.aliyuncs.com
          username: ${{ secrets.CT_ALIYUN_USER }}
          password: ${{ secrets.CT_ALIYUN_PASS }}

      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/admin-v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./web/admin
          file: ./web/admin/Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/admin-v') }}
          tags: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/panda-wiki-nginx:${{ steps.get_version.outputs.VERSION }}

  docker-app-build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/app-') || startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/app-v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        if: startsWith(github.ref, 'refs/tags/app-v')
        uses: docker/login-action@v3
        with:
          registry: chaitin-registry.cn-hangzhou.cr.aliyuncs.com
          username: ${{ secrets.CT_ALIYUN_USER }}
          password: ${{ secrets.CT_ALIYUN_PASS }}

      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/app-v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./web/app
          file: ./web/app/Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/app-v') }}
          tags: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/panda-wiki-app:${{ steps.get_version.outputs.VERSION }}
